import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/store/Provider";
import Header from "@/components/header/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
					rel="stylesheet"
				/>
			</head>
			<body>
				<StoreProvider>
					<Header />
					{children}
				</StoreProvider>
			</body>
		</html>
	);
}
